name: MapImageEngine
main: FaigerSYS\MapImageEngine\MapImageEngine
version: "1.1-ALPHA1"
api: ["3.0.0-ALPHA9", "3.0.0-ALPHA10", "3.0.0-ALPHA11"]
load: POSTWORLD
author: FaigerSYS
description: "Image engine for MCPE servers"

permissions:
  mapimageengine:
    default: op
    description: "Allows command usage (/mie)"
